# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            HyunJung Kim
tagline:          'Student Journalist and PR Lover'
description:      A future journalist and PR specialist who focuses on a deep insight and cares about diversity.
url:              http://hkim60.github.io
baseurl:          /profile-hyde/
shortbaseurl:     /profile-hyde
colorscheme:      ''
#options '' (black), theme-base-08 (red), theme-base-09 (orange), theme-base-0a (yellow), theme-base-0b (green), theme-base-0c (cyan), theme-base-0d (blue), theme-base-0e (magenta), theme-base-0f (brown)


author:
  name:           'HyunJung Kim'
  url:            ''
  
paginate:         5

# Custom vars
version:          0.8.1

